trigger:
- main  # or use the branch name where you place this file

pool:
  name: linux-org  # match your agent pool name

jobs:
- job: HelloWorld
  steps:
    - script: echo "Hello, world from self-hosted agent!"
      displayName: Say Hello

